package com.bksgames.game.globalClasses.enums;

public enum Displayable {
    WALL, RED_NEXUS, BLUE_NEXUS, TUNNEL, RED_MINION, BLUE_MINION,
    RED_MIRROR_SLASH, RED_MIRROR_BACKSLASH,
    BLUE_MIRROR_SLASH, BLUE_MIRROR_BACKSLASH,
    STRAIGHT_LASER, BENT_LASER
}
